[features]
seeds = false
skip-lint = false
[programs.localnet]
bridge = "6zWU7bEZ1BndvfraVqNyHeuyn5Go8HjtYxEk4ZHR1P1k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jonathanmedina/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
